<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class contract_management extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>1
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>2
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>3
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>4
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>5
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>6
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>7
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>8
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>9
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>10
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>11
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>12
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>13
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>14
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>3,
            'macro_product_id'=>15
        ]);

        DB::table('contract_managements')->insert([
            'user_id'=>4,
            'macro_product_id'=>12
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>4,
            'macro_product_id'=>13
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>4,
            'macro_product_id'=>14
        ]);

        DB::table('contract_managements')->insert([
            'user_id'=>5,
            'macro_product_id'=>1
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>5,
            'macro_product_id'=>2
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>5,
            'macro_product_id'=>3
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>5,
            'macro_product_id'=>4
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>5,
            'macro_product_id'=>8
        ]);


        DB::table('contract_managements')->insert([
            'user_id'=>6,
            'macro_product_id'=>5
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>6,
            'macro_product_id'=>6
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>6,
            'macro_product_id'=>7
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>6,
            'macro_product_id'=>15
        ]);


        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>1
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>2
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>3
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>4
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>5
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>6
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>7
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>8
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>9
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>10
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>11
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>12
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>13
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>14
        ]);
        DB::table('contract_managements')->insert([
            'user_id'=>7,
            'macro_product_id'=>15
        ]);
    }
}
